### ISSUE TITLE
Is there a way to launch an external executable from artifactcollector?

### ISSUE THREAD

**Issue by tatsu-i** [forensicanalysis/artifactcollector#20]
For example, I want to launch an exe file that performs a Yara scan of the process from artifactcollector and include the output log in the archive

**Comment by cugu** [comment]
Yes. You can add the executable to `pack/bin/` and then run `go generate`. 

Also add a COMMAND artifact e.g.:
``` yaml
name: Autoruns
sources:
- type: COMMAND
  attributes:
    cmd: autorunsc.exe
    args: ["-x"]
supported_os: [Windows]
```

Currently the output to stdout and stderr is saved, but generated files are not collected.
