### ISSUE TITLE
About output file classification

### ISSUE THREAD

**Issue by tatsu-i** [forensicanalysis/artifactcollector#25]
Is it possible to create a directory for each type of artifact (eg Evtx, Registry, etc.)?

For example:

artifacts.yaml
``` yaml
name: DefaultEntryPoint
doc: Windows Forensic Analysis
sources:
- type: ARTIFACT_GROUP
  attributes:
    names:
    - Prefetch
    - NTFS
    - Registry
    - Web
    - Evtx
  supported_os: [Windows]
supported_os: [Windows]

---
name: Evtx
sources:
- type: ARTIFACT_GROUP
  attributes:
    names:
    - WindowsXMLEventLogApplication
    - WindowsXMLEventLogSecurity
    - WindowsXMLEventLogSystem
    - WindowsXMLEventLogSysmon
    - WindowsXMLEventLogTerminalServices
supported_os: [Windows]

---
name: Web
sources:
- type: ARTIFACT_GROUP
  attributes:
    names:
    - InternetExplorerHistory
    - FirefoxHistory
    - ChromeHistory
supported_os: [Windows]

---
name: Registry
sources:
- type: ARTIFACT_GROUP
  attributes:
    names:
    - WindowsAMCacheHveFile
    - WindowsSystemRegistryFiles
    - WindowsUserRegistryFiles
supported_os: [Windows]

---
name: NTFS
sources:
- type: ARTIFACT_GROUP
  attributes:
    names:
    - NTFSMFTFiles
supported_os: [Windows]

---
name: Prefetch
sources:
- type: ARTIFACT_GROUP
  attributes:
    names:
    - WindowsPrefetchFiles
supported_os: [Windows]
```

Output result
```
example.forensicstore/
├── Registry
│   ├── SYSTEM
│   ├── Amcache.hve
│   └── ...
├── Web
│   └──  ...
├── Evtx
│   ├──  Application.evtx
│   ├──  System.evtx
│   ├──  Security.evtx
│   └──  ...
├── ...
└── item.db
```
