### ISSUE TITLE
File name is truncated

### ISSUE THREAD

**Issue by tatsu-i** [forensicanalysis/artifactcollector#51]
When I collected EVTX with the following settings, some file names were truncated.
I could not determine what the log was even by looking at the file name after collection.

This seems to be related to file name duplication and the maximum number of characters in the file path, but if possible, I would like a mechanism that can switch the saving with a relative file name as before with an option.

```
name: Evtx
doc: Windows Event logs.
sources:
- type: FILE
  attributes:
    paths:
      - '%%environ_systemroot%%\System32\winevt\Logs\Application.evtx'
      - '%%environ_systemroot%%\System32\winevt\Logs\Security.evtx'
      - '%%environ_systemroot%%\System32\winevt\Logs\System.evtx'
      - '%%environ_systemroot%%\System32\winevt\Logs\*PowerShell*.evtx'
      - '%%environ_systemroot%%\System32\winevt\Logs\Microsoft-Windows-Sysmon%4Operational.evtx'
      - '%%environ_systemroot%%\System32\winevt\Logs\Microsoft-Windows-TaskScheduler%4Operational.evtx'
      - '%%environ_systemroot%%\System32\winevt\Logs\Microsoft-Windows-TerminalServices-LocalSessionManager%4Operational.evtx'
    separator: '\'
conditions: [os_major_version >= 6]
supported_os: [Windows]
urls: ['http://www.forensicswiki.org/wiki/Windows_XML_Event_Log_(EVTX)']

```

![f](https://user-images.githubusercontent.com/2360691/81663369-992c6a80-9479-11ea-9cf0-fafe3d7e2d71.png)

Is it possible to include an option to switch to saving with a relative filename as before?

```
C_Windows_System32_winevt_Logs_Application.evtx -> Application.evtx
```
